### PR TITLE
Initial proposal

### PR DESCRIPTION
**Pull request by fw42**
Big PR (most of it is the theme).

Look at the last commit only to see the actual content.

Or better, clone the repo and run

```
gem install bundler
bundle install
jekyll serve -w
```

to see the generated HTML output in your own browser.

This is a simple single-page Jekyll page. Uses [SinglePaged](https://github.com/t413/SinglePaged) (MIT license) and [this icon](https://www.iconfinder.com/icons/55827/lock_padlock_private_icon#size=512) as a logo (free for private and commercial use).

Looks something like this:

screen shot 2015-05-06 at 10 44 47 pm

There is still some content missing. Wasn't sure what you would want on a page like that. 

Hope you like the theme.

@fd0, @ckeen, please take a look.

### CODE REVIEW

**Comment by fw42** [comment]
Some more screenshots:

screen shot 2015-05-06 at 10 44 56 pm

screen shot 2015-05-06 at 10 45 03 pm

screen shot 2015-05-06 at 10 45 11 pm

**Comment by ckeen** [comment]
Looks good to me! Thanks for your effort!

**Comment by fd0** [comment]
Thanks a lot for getting this started! I'm very grateful for that, I suck at building websites (it's just not my thing). I like the content that you put in so far (apart from the FAQ ;).

To be honest, I must say that I unfortunately don't like the website template at all. I know that it's recently very popular to have a scrolling website in this style, but there are quite some negative points:
- It's a lot to scroll with little text and little information on it. This reminds me of these annoying classic forums like PHPBB, where people tend to have signatures that are three times the length of their contribution to the discussion thread. It's simply not a good ratio (page length vs. actual content).
- The colors are beautiful, but very flashy, and I find white text especially on blue and green very hard to read.
- The parts where a shell or code is display should be more set apart from the rest, maybe with a darker grey background or so.
- The website template doesn't allow much content on the site, but I think we need that rather soon (see below).

In order to be constructive, I've thought about what should be on the website for the first release, and what do we maybe need later on.

These are my main thoughts for the website for the first release:
- The front page should display a mini-tutorial, just installing, `restic init`, `restic backup`, `restic restore` etc., in order to get started really.
- There must be some kind of user-manual/reference, maybe we can use the same source to generate the manpage for restic
- There should be a video of a talk explaining the usage, maybe the Froscon one once it's released

Maybe we could integrate a blog later on, where interesting infrastructure things are explained in greater detail.

Regarding the design, I really like the http://www.passwordstore.org and http://msgpack.org, maybe we can find a theme that's similar to those pages.

**Comment by fw42** [comment]
btw., http://www.passwordstore.org/ uses the default github-pages theme

**Pull request closed without merging**
