### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by bchapuis**
Very good and easy to follow introduction. I just got an 'unknown flag' message at initialization phase and a 'wrong number of argument' message at restore phase. Thank you for the great work.

### CODE REVIEW

**Comment by fd0** [comment]
Thanks for your contribution! I have a few comments that can be addressed right away, if you don't mind changing a few more lines ;)

Are you maybe also interested to add an example for the fuse mount to the mini tutorial?

**Comment by bchapuis** [comment]
I would be glad to help :)
What do you have in mind regarding the fuse mount mini tutorial? I had a look at the fuse folder in the sources but I'm totally new to Go programming. Does restic has some internal support for fuse?

**Comment by fd0** [comment]
Oh, I'm sorry. That's another hint that the user documentation must be improved (or even written) ;)

Since about a week, restic has support for mounting the repository to a directory, so the tutorial should have an additional step where the repo is mounted and an `ls` and `cp` command is shown, e.g. like this:

```
$ restic -r /tmp/backup mount /mnt/restic
$ ls -al /mnt/restic/snapshots/
```

etc. The second command must be executed in a second terminal, as restic blocks while serving the fuse mount.

For all files and directories that are accessed via the mounted fuse fs, all content is fetched on demand only, so it's safe to browse a remote repo with huge files in it.

**Comment by bchapuis** [comment]
It seems to work pretty well :)

**Comment by fd0** [comment]
Looks good, thanks!

**Pull request merged**
